DROP TABLE event_history CASCADE;
DROP TABLE event CASCADE;
DROP TABLE graph CASCADE;
DROP TABLE graphgroup CASCADE;
DROP TABLE graphtogroups CASCADE;
DROP TABLE "group" CASCADE;
DROP TABLE host CASCADE;
DROP TABLE hostgroup CASCADE;
DROP TABLE perfdatasource CASCADE;
DROP TABLE permission CASCADE;
DROP TABLE service CASCADE;
DROP TABLE servicegroup CASCADE;
DROP TABLE hostservicedata CASCADE;
DROP TABLE highlevelservice CASCADE;
DROP TABLE highlevelservicedep CASCADE;
DROP TABLE state CASCADE;
DROP TABLE "user" CASCADE;
DROP TABLE usergroup CASCADE;
DROP TABLE version CASCADE;
DROP TABLE tag CASCADE;
DROP TABLE eventsaggregate CASCADE;
DROP TABLE boardviewfilter CASCADE;
DROP TABLE customgraphview CASCADE;
DROP TABLE "access" CASCADE;

DROP TABLE link CASCADE;
DROP TABLE "map" CASCADE;
DROP TABLE nodemap CASCADE;
DROP TABLE segment CASCADE;
DROP TABLE "session" CASCADE;

DROP TABLE usergrouppermissions CASCADE;
DROP TABLE tags2hosts CASCADE;
DROP TABLE tags2services CASCADE;
DROP TABLE eventsaggregates2events CASCADE;
DROP TABLE eventsaggregate2hls CASCADE;
DROP TABLE grouppermissions CASCADE;
DROP TABLE usertousergroups CASCADE;
DROP TABLE segmentnodetable;
DROP TABLE mapgrouppermissions;
DROP TABLE mapgroupmaptable;
DROP TABLE submapnodemaptable;

