TRUNCATE TABLE event_history CASCADE;
TRUNCATE TABLE event CASCADE;
TRUNCATE TABLE graph CASCADE;
TRUNCATE TABLE graphgroup CASCADE;
TRUNCATE TABLE graphtogroups CASCADE;
TRUNCATE TABLE "group" CASCADE;
TRUNCATE TABLE host CASCADE;
TRUNCATE TABLE hostgroup CASCADE;
TRUNCATE TABLE perfdatasource CASCADE;
TRUNCATE TABLE permission CASCADE;
TRUNCATE TABLE service CASCADE;
TRUNCATE TABLE servicegroup CASCADE;
TRUNCATE TABLE hostservicedata CASCADE;
TRUNCATE TABLE highlevelservice CASCADE;
TRUNCATE TABLE highlevelservicedep CASCADE;
TRUNCATE TABLE state CASCADE;
TRUNCATE TABLE "user" CASCADE;
TRUNCATE TABLE usergroup CASCADE;
TRUNCATE TABLE version CASCADE;
TRUNCATE TABLE tag CASCADE;
TRUNCATE TABLE eventsaggregate CASCADE;
TRUNCATE TABLE boardviewfilter CASCADE;
TRUNCATE TABLE customgraphview CASCADE;
TRUNCATE TABLE "access" CASCADE;

TRUNCATE TABLE link CASCADE;
TRUNCATE TABLE "map" CASCADE;
TRUNCATE TABLE nodemap CASCADE;
TRUNCATE TABLE segment CASCADE;
TRUNCATE TABLE "session" CASCADE;

TRUNCATE TABLE usergrouppermissions CASCADE;
TRUNCATE TABLE tags2hosts CASCADE;
TRUNCATE TABLE tags2services CASCADE;
TRUNCATE TABLE eventsaggregates2events CASCADE;
TRUNCATE TABLE eventsaggregate2hls CASCADE;
TRUNCATE TABLE grouppermissions CASCADE;
TRUNCATE TABLE usertousergroups CASCADE;
TRUNCATE TABLE segmentnodetable CASCADE;
TRUNCATE TABLE mapgrouppermissions CASCADE;
TRUNCATE TABLE mapgroupmaptable CASCADE;
TRUNCATE TABLE submapnodemaptable CASCADE;





